apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: {{.Release.Name}}
  name: {{.Release.Name}}
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.Release.Name}}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{.Release.Name}}
      name: {{.Release.Name}}
    spec:
      serviceAccountName: {{.Release.Name}}
      containers:
      - name: {{.Release.Name}}
        image: {{.Values.image}}
        imagePullPolicy: Always
        resources:
          limits:
            memory: {{.Values.limits.memory}}
          requests:
            memory: {{.Values.requests.memory}}
        volumeMounts:
        - name: config-volume
          mountPath: /src/resources/application.yml
          subPath: application.yml
      volumes:
      - name: config-volume
        configMap:
          name: {{.Release.Name}}
