apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{.Release.Name}}
  namespace: kube-system
{{- if .Values.ingress.annotations }}
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4 }}
{{- end }}
spec:
  rules:
  - host: "{{.Release.Name}}.dev.contaazul.local"
    http:
      paths:
      - backend:
          serviceName: {{.Release.Name}}
          servicePort: 80
