image: felipecrestani/turbine:latest
limits:
  memory: 300Mi
requests:
  memory: 300Mi

ingress:
  annotations:
    kubernetes.io/ingress.class: traefik
    external-dns.alpha.kubernetes.io/target: traefik.dev.contaazul.local.
  host: turbine.dev.contaazul.local
